---
title: "R Notebook"
output: html_notebook
---

first look
```{r}
library(readxl)
library(tidyverse)
library(janitor)

candy_2015 <- read_excel("raw_data/boing-boing-candy-2015.xlsx") 
candy_2015 <- clean_names(candy_2015)
org_names2015 <- names(candy_2015)

#rename column to avoid matching with mars
candy_2015 <- rename(candy_2015, those_odd_MARShmallow_circus_peanut_things =
                        those_odd_marshmallow_circus_peanut_things) 
names2015 <- names(candy_2015)
names2015

```

```{r}
#identify all columns that contain a 'candy' these are items where columns have ratings as JOY or DESPAIR or NA but nothing else - do this by counting entries
count_candy <- candy_2015 %>% 
    summarise(across(everything(),   ~{sum(.x %in% c("JOY","DESPAIR"))}  ))
# this filters out random instances of joy and despair in non-candy columns
is_candy <- which(count_candy>0.25*nrow(candy_2015)) 
```

```{r}
candy_2016 <- read_excel("raw_data/boing-boing-candy-2016.xlsx") 
candy_2016 <- clean_names(candy_2016)
org_names2016 <- names(candy_2016)

# rename this - do we need it?
candy_2016 <- rename(candy_2016,BONKERS_THE_BOARD_GAME = bonkers_the_board_game)
# rename extra licorice columns for now until we work out what to do with it
candy_2016 <- rename(candy_2016,LICORICE_YES_BLACK = licorice_yes_black)
# rename extra peppermint columns for now until we work out what to do with it
candy_2016 <- rename(candy_2016,YORK_peppermint_patties_ignore = york_peppermint_patties_ignore)
#rename this to avoid matching with mars
candy_2016 <- rename(candy_2016, those_odd_MARShmallow_circus_peanut_things =
                        those_odd_marshmallow_circus_peanut_things)
names2016 <- names(candy_2016)
names2016
```
```{r}
candy_2017 <- read_excel("raw_data/boing-boing-candy-2017.xlsx") 
candy_2017 <- clean_names(candy_2017)
org_names2017 <- names(candy_2017)

#remove 'q_' numbers from columnn names
for (cols in 1:length(candy_2017)) {
  names(candy_2017)[names(candy_2017)==org_names2017[cols]] <- str_remove(org_names2017[cols],"[q][1-9]+[_]")
}
#rename(candy_2017, (str_sub(names2017[cols],start=4)) = names2017[cols])   

# rename problematic columns to help match
candy_2017 <- rename(candy_2017,BONKERS_THE_BOARD_GAME = bonkers_the_board_game)
candy_2017 <- rename(candy_2017,LICORICE_YES_BLACK = licorice_yes_black)
#rename this to avoid matching with mars
candy_2017 <- rename(candy_2017,those_odd_MARShmallow_circus_peanut_things =
                        those_odd_marshmallow_circus_peanut_things)
names2017 <- names(candy_2017)
names2017
```



```{r}
# all datasets have a set of demographic questions - match them here
org_names2015[1:5]
candy_2015 <- candy_2015 %>% 
  rename(age_question = how_old_are_you) %>% 
  rename(tot_question = are_you_going_actually_going_trick_or_treating_yourself)

org_names2016[1:5]
candy_2016 <- candy_2016 %>% 
  rename(age_question = how_old_are_you) %>% 
  rename(tot_question = are_you_going_actually_going_trick_or_treating_yourself) %>% 
  rename(country_question = which_country_do_you_live_in) %>% 
  rename(gender_question = your_gender)

names2017[1:5]
candy_2017 <- candy_2017 %>% 
  rename(age_question = age) %>% 
  rename(tot_question = going_out) %>% 
  rename(country_question = country) %>% 
  rename(gender_question = gender) 

```

```{r}
names2015 = names(candy_2015)
names2016 = names(candy_2016)
names2017 = names(candy_2017)

matchtable <- matrix(NA,nrow=length(names2015),ncol=3)
for (cols in 1:length(names2015)){
  matchnum1 = NA
  matchnum2 = NA
  if (sum(str_detect(names2016,names2015[cols])>0))
    {matchnum1=which((str_detect(names2016,names2015[cols])))
  } else {
      print(paste("no match for 2016 at cols",cols))}
  
  if (sum(str_detect(names2017,names2015[cols])>0))
    {matchnum2=which((str_detect(names2017,names2015[cols])))
  } else {
      print(paste("no match for 2017 at cols",cols))}
  
  if (length(matchnum1)>1){
     print(paste("multiple matches found at cols",cols))
     print(paste("2015 data:", names2015[cols]))
     print(paste("2016 data:", names2016[matchnum1[1]]))
     print(paste("2016 data:", names2016[matchnum1[2]]))
     return() }
  
  if (length(matchnum2)>1){
     print(paste("multiple matches found at cols",cols))
     print(paste("2015 data:", names2015[cols]))
     print(paste("2017 data:", names2017[matchnum2[1]]))
     print(paste("2017 data:", names2017[matchnum2[2]]))
     return() }
  
  matchtable[cols,c(1:3)]=c(cols,matchnum1,matchnum2)
}
```
```{r}
#list of columns that are a direct match in all three datastets
matchtable <- as_tibble(matchtable)
drop_na(matchtable)
```
```{r}
#list of columns that are in 2015 data but not in 2016 and/or 2017
matchtable  %>% 
 mutate(na_count = is.na(V1)+is.na(V2)+is.na(V3)) %>% 
 filter(na_count > 0)
```

```{r}
clean_candy_2017 %>% 
  select(contains("demog"))
```




